### PR TITLE
Only 1 test fails and and probably 1 assertion failed in boost.

### PR DESCRIPTION
**Pull request by kenkit**
I will make the testfiles to get generated to the binary dir.
~~Could use some help with that conversion.~~

### CODE REVIEW

**Comment by kenkit** [comment]
Now builds are ok, the only thing remain is to verify if testing works as expected considering the many changes.
The test executable is working right.

**Comment by kenkit** [comment]
To make things more fun. We can use cmake to find 7z and add  it to a header where the app will pick it from.

**Comment by getnamo** [comment]
It's been a while since I've properly reviewed this repo, but I believe Boost is only required for the test suite, is it possible to have a conditional cmakelist that ignores the test target if boost is not found? (I'd like to keep the main library not depending boost and still generate the .sln for builds).

Otherwise a lot of these changes look great for robustness.

**Comment by kenkit** [comment]
Yes it's possible, currently boost is not required to build the library.
Infact It's not required in order to build.
You can just generate the sources then run cmake --build build_dir --target 7zpp
I don't expect you to find a build error when doing this.
I'll try to see if it's possible to skip building the test app if boost is not found.

**Comment by kenkit** [comment]
I think that should work, I have not tested without boost.

**Comment by getnamo** [comment]
Confirmed works without boost as expect, will cleanup readme a little bit to add basic instructions to replicate build

**Pull request merged**
