### PR TITLE
Proper cmake usage instructions

### PR DESCRIPTION
**Pull request by kenkit**

### CODE REVIEW

**Comment by kenkit** [comment]
You can just create an appveyor account and add this project to your appveyor account.
You won't have to change anything for it to work, just remember to update the github badge. 
Overtime I think we/someone will be able to fix that failing test.

**Comment by getnamo** [comment]
1) Clarified boost section. It is optional, someone coming fresh to the repo should be able to build without any dependencies.

2) Missing steps to build 64 bit & release builds via cmake. Using e.g. 
``` 
cmake -DCMAKE_GENERATOR_PLATFORM=x64 . 
```
and then building gives
LNK1112: module machine type 'x64' conflicts with target machine type 'x86' what's the correct way to build a different config?

**Comment by getnamo** [comment]
Found working commands, defaulted to these in readme as they build the most expected build and hint at how to change targets/config pairs

**Comment by getnamo** [comment]
merging, feel free to modify readme if you feel like there should be more instructions. I'll look into shrinking the initial build commands by using .gitkeep on /build

**Pull request merged**
